// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mndbalflwdqkzoejitfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZGJhbGZsd2Rxa3pvZWppdGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODczOTQsImV4cCI6MjA2Nzk2MzM5NH0.pv2M-lfKBpge94tycQKFEW-wM0no8T1Jzipv5_OAX7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});